In [1]:
import numpy as np
import pandas as pd

In [2]:
city_count = 4 # the number of cities
population_size = 20 # the size of population
item_number_max = 3
volocity_MAX, volocity_MIN, volocity_current = 0.0, 0.0, 0.0
knapsack_Max, knapsack_MIN, knapsack_current =0.0, 0.0, 0.0

A structure that stores the information about the weight and value that every item has in each city. Each city have n items, and n is the largest number of items that exist in each city. For example, there are four cities which have 2,3,3,3 items respectively. For city0, in the structure, the weight and value of its item2 are NaN, which means the item2 do not exsist.

In [3]:
iterables = [['0','1','2','3'],['0','1','2']]
multi_idx = pd.MultiIndex.from_product(iterables,names=['cityIndex','itemIndex'])
data_weight = [1,4,np.nan,4,6,3,7,3,5,8,9,4]
data_value = [2,6,np.nan,6,7,4,9,4,6,8,9,5]
itemList = pd.DataFrame(data_weight, index=multi_idx,columns=['weight'])
itemList['value'] = data_value
itemList

weight  value
cityIndex itemIndex               
0         0             1.0    2.0
          1             4.0    6.0
          2             NaN    NaN
1         0             4.0    6.0
          1             6.0    7.0
          2             3.0    4.0
2         0             7.0    9.0
          1             3.0    4.0
          2             5.0    6.0
3         0             8.0    8.0
          1             9.0    9.0
          2             4.0    5.0

#### **Index a specific weight or value**
For example, to obtain the weight of item2 in city0.

In [4]:
print(itemList['weight']['0']['2'],type(itemList['weight']['0']['2']))

nan <class 'numpy.float64'>


#### **Distance matrix and solution of TSP part**

In [5]:
distanceMatrix = np.zeros((city_count,city_count))
pathMatrix = np.zeros((population_size,city_count))
path_individual = pathMatrix[0]

#### **Decision matrix of items**

In [6]:
decisionMatrix = np.zeros((population_size,city_count,item_number_max),dtype=int)
decision_individual = decisionMatrix[0]
decision_individual

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

One solution is a combination of decision_individual and path_individual. When calculating the fitness of solution[0], we can first obtain its decision of items, through decisionMatrix[0][0] and its path, through pathMatrix[0]. Then we can use item list to calculate the total profits via def calculateProfit() and the total time via def calculateTime().

#### **Funcitions to calculate profits and time**

In [7]:
def calculateProfit(path,decision):
    profit = 0.0
    for i in path:#[1,3,2,0]
        index = 0
        for k in decision[i]:#0,1,0
            if k == 1:
                profit += itemList['value'][str(i)][str(index)]
            index += 1 
    return profit


In [ ]:
def calculateKnapsack():
    pass

In [ ]:
def calculateVelocity():
    pass

In [8]:
def calculateTime():
    pass

#### **Test calculateProfit()**

In [9]:
path_test = np.zeros((population_size,city_count),dtype=int)
path_test = path_test[0]
path_test = np.array([1,3,2,0])
path_test

array([1, 3, 2, 0])

In [10]:
decision_test = np.zeros((population_size,city_count,item_number_max),dtype=int)
decision_test[0][0][1] = 1
decision_test[0][2][0] = 1
decision_test = decision_test[0]
decision_test

array([[0, 1, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [11]:
# test calculateProfit()
profit_current = calculateProfit(path_test,decision_test)
profit_current

15.0